/**
 * @file    mfrc522_demo.h
 * @brief   Shared helpers for the example programs.
 *
 * Provides a tiny printf-over-UART console (`demo_printf`) and declares the
 * STM32CubeMX-generated init functions each example relies on. This header is
 * for the EXAMPLES only — it uses printf/stdlib and is NOT part of the core
 * library (the core never calls printf).
 *
 * Each example is written as a self-contained main.c that you drop into a
 * STM32CubeIDE / CubeMX project. The project must provide the usual generated
 * functions (SystemClock_Config, MX_GPIO_Init, MX_SPI1_Init, ...) and the
 * peripheral handles (hspi1, huart3, ...). See examples/README.md.
 */

#ifndef MFRC522_DEMO_H
#define MFRC522_DEMO_H

#include <stdio.h>
#include <string.h>
#include "mfrc522.h"

/* ---- STM32 HAL (for the UART console in the examples) ------------- */
#if defined(STM32H743xx) || defined(STM32H750xx) || defined(STM32H753xx)
#include "stm32h7xx_hal.h"
#elif defined(STM32F4xx)
#include "stm32f4xx_hal.h"
#else
#include "stm32h7xx_hal.h"
#endif

/* ---- STM32 platform adapter (declares MFRC522_STM32_*_Init) ------- */
#include "mfrc522_stm32_spi.h"
#include "mfrc522_stm32_i2c.h"
#include "mfrc522_stm32_uart.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/*  Debug console (printf over the configured UART)                    */
/* ------------------------------------------------------------------ */

/**
 * @brief Debug UART used by demo_printf(). Override by defining
 *        MFRC522_DEMO_UART before including this header (e.g. &huart2).
 */
#ifndef MFRC522_DEMO_UART
#define MFRC522_DEMO_UART (&huart3)
#endif

/**
 * @brief printf-style output over the demo UART (blocking).
 */
void demo_printf(const char *fmt, ...);

/* ------------------------------------------------------------------ */
/*  CubeMX-generated functions the examples depend on                 */
/*  (provided by the STM32CubeIDE project — not by this library)       */
/* ------------------------------------------------------------------ */

void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_SPI1_Init(void);
void MX_I2C1_Init(void);
void MX_USART3_UART_Init(void);
void Error_Handler(void);

/* Peripherals / pins (also generated by CubeMX; the examples reference
 * these names — adjust them to match your project). */
extern SPI_HandleTypeDef  hspi1;
extern I2C_HandleTypeDef  hi2c1;
extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart3;

extern GPIO_TypeDef *RFID_CS_GPIO_Port;
extern uint16_t      RFID_CS_Pin;
extern GPIO_TypeDef *RFID_RST_GPIO_Port;
extern uint16_t      RFID_RST_Pin;
extern GPIO_TypeDef *RFID_IRQ_GPIO_Port;
extern uint16_t      RFID_IRQ_Pin;

/**
 * @brief Canonical demo key: the MIFARE Classic factory default.
 */
static const MFRC522_Key_t DEMO_KEY =
    { { 0xFFu, 0xFFu, 0xFFu, 0xFFu, 0xFFu, 0xFFu } };

#ifdef __cplusplus
}
#endif

#endif /* MFRC522_DEMO_H */
